#!/bin/bash
sudo /usr/bin/python3 -m pip install fire
sudo cp -r $(pwd) /usr/local/bin

echo "[Unit]
Description=brightness control script

[Service]
ExecStart=/usr/local/bin/brightness_control/set_default
Restart=on-failure

[Install]
WantedBy=multi-user.target" | sudo tee /etc/systemd/system/brightness-control-py.service

sudo systemctl daemon-reload
sudo systemctl enable brightness-control-py.service
sudo systemctl start brightness-control-py.service
